project:
    type: website
    output-dir: docs
    title: "Beyond the Dataset"
    resources:
        - static/resume/Software_Resume.pdf

website:
    title: "Beyond the Dataset"
    description: "A blog about data science, machine learning, mlops, and software engineering."
    site-url: https://sagarthacker.com
    page-navigation: true
    google-analytics: "G-17YZDMEKH1"
    navbar:
        pinned: true
        left:
            - href: index.qmd
              text: Home
            - href: about.qmd
              text: About
        right:
            - icon: github
              href: https://www.github.com/sagar118
            - icon: linkedin
              href: https://www.linkedin.com/in/sagar-thacker/
            - icon: envelope
              href: "mailto:sagar+site@sagarthacker.com"
    page-footer:
        left: "Made with [Quarto](https://quarto.org/), by Sagar Thacker. License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
        right:
            - icon: github
              href: https://www.github.com/sagar118
            - icon: linkedin
              href: https://www.linkedin.com/in/sagar-thacker/
            - icon: envelope
              href: "mailto:sagar+site@sagarthacker.com"
    twitter-card:
        creator: "@sagarthacker118"
        site: "@sagarthacker"

format:
    html:
        theme: flatly
        css: styles.css
        toc: true
        page-layout: article
        link-external-icon: true
        link-external-newwindow: true
        link-external-filter: (?:http:|https:)\/\/(www\.)?sagarthacker\.com\/*|javascript\:void\(0\)
        citations-hover: true
        footnotes-hover: true
        code-link: true
        code-line-numbers: true
        code-block-background: true
        code-summary: "Show the code"
        code-tools:
            source: false
            toggle: true