project:
    type: website
    output-dir: docs
    resources:
        - static/resume/Software_Resume.pdf

website:
    title: "Sagar Thacker"
    site-url: https://sagarthacker.com
    page-navigation: true
    google-analytics: "G-17YZDMEKH1"
    navbar:
        pinned: true
        left:
            - href: index.qmd
              text: Home
            - href: about.qmd
              text: About
        right:
            - icon: github
              url: https://www.github.com/sagar118
            - icon: linkedin
              url: https://www.linkedin.com/in/sagar-thacker/
            - icon: envelope
              url: "mailto:sagar+site@sagarthacker.com"
    page-footer:
        left: "Made with [Quarto](https://quarto.org/), by Sagar Thacker. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
        right:
            - icon: github
              url: https://www.github.com/sagar118
            - icon: linkedin
              url: https://www.linkedin.com/in/sagar-thacker/
            - icon: envelope
              url: "mailto:sagar+site@sagarthacker.com"

format:
    html:
        theme: flatly
        css: styles.css
        toc: true
        page-layout: article
        link-external-icon: true
        link-external-newwindow: true
        link-external-filter: (?:http:|https:)\/\/(www\.)?sagarthacker\.com\/*|javascript\:void\(0\)
        citations-hover: true
        footnotes-hover: true
        code-link: true
        code-tools:
            source: false
            toggle: true
